AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Resources for the AWS OpsWorks Configuration Manager preview.
Outputs:
  InstanceProfileArn:
    Description: InstanceProfileArn
    Value: !GetAtt [InstanceProfile, Arn]
  ServiceRoleArn:
    Description: ServiceRoleArn
    Value: !GetAtt [ServiceRole, Arn]

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      -  arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
              - ec2.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:AbortMultipartUpload
            - s3:DeleteObject
            - s3:GetObject
            - s3:ListAllMyBuckets
            - s3:ListBucket
            - s3:ListMultipartUploadParts
            - s3:PutObject
            Effect: Allow
            Resource: arn:aws:s3:::aws-opsworks-cm-*
          Version: '2012-10-17'
        PolicyName: InstancePolicy
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - Ref: InstanceRole
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
              - opsworks-cm.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:CreateBucket
            - s3:DeleteBucket
            - s3:DeleteObject
            - s3:GetObject
            - s3:HeadBucket
            - s3:ListBucket
            - s3:ListObjects
            Resource: arn:aws:s3:::aws-opsworks-cm-*
            Effect: Allow
          - Action:
            - ssm:SendCommand
            Condition:
              StringLike:
                ssm:resourceTag/aws:cloudformation:stack-name:
                - aws-opsworks-cm-*
            Resource: "*"
            Effect: Allow
          - Action:
            - ssm:SendCommand
            Resource:
              - arn:aws:ssm:*::document/*
              - arn:aws:s3:::aws-opsworks-cm-*
            Effect: Allow
          - Action:
            - ssm:DescribeInstanceInformation
            - ssm:ListCommandInvocations
            - ssm:ListCommands
            Resource: "*"
            Effect: Allow
          - Action:
            - iam:PassRole
            Resource: arn:aws:iam::*:role/aws-opsworks-cm*
            Effect: Allow
          - Action:
            - ec2:CreateSecurityGroup
            - ec2:AuthorizeSecurityGroupIngress
            - ec2:RunInstances
            - ec2:DescribeAccountAttributes
            - ec2:DescribeInstanceStatus
            - ec2:DescribeSecurityGroups
            - ec2:createTags
            - ec2:AllocateAddress
            - ec2:AssociateAddress
            - ec2:DescribeInstances
            - ec2:DescribeAddresses
            - ec2:DescribeSubnets
            - ec2:DeleteSecurityGroup
            - ec2:DisassociateAddress
            - ec2:ReleaseAddress
            Resource: "*"
            Effect: Allow
          - Action:
            - ec2:TerminateInstances
            Resource: "*"
            Condition:
              StringLike:
                ec2:ResourceTag/aws:cloudformation:stack-name: aws-opsworks-cm-*
            Effect: Allow
          - Action:
            - cloudformation:CreateStack
            - cloudformation:UpdateStack
            - cloudformation:DescribeStacks
            - cloudformation:DescribeStackEvents
            - cloudformation:DeleteStack
            - cloudformation:DescribeStackResources
            Resource: arn:aws:cloudformation:*:*:stack/aws-opsworks-cm-*
            Effect: Allow
          Version: '2012-10-17'
        PolicyName: OpsWorksCMPolicy
